before_script: 'bundle install --gemfile=test/rails2/Gemfile'
before_script: 'bundle install --gemfile=test/rails3/Gemfile'

rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.2
  #- 1.9.3
  - ree
  - rbx
  - rbx-2.0
  - jruby
